# tasks file for ansible-role-packages
---
- name: Update system
  become: true
  pacman:
    update_cache: true
    upgrade: true

- name: Install packages
  become: true
  package:
    name: "{{ languages }}"
    state: present
